# We are setting the port where our application will run
server.port=8080

# --- DATABASE CONFIGURATION ---
# We are telling our app to connect to an in-memory H2 database named 'paymentdb'
spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# --- TRANSLATOR CONFIGURATION (JPA/Hibernate) ---
# This is a VERY powerful setting. 'update' means:
# "Look at my Java code. If a database table is missing, create it automatically!"
spring.jpa.hibernate.ddl-auto=update

# We turn this on so we can see the exact SQL code our translator is writing in the console logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- H2 CONSOLE ---
# This turns on a web page so we can visually look inside our temporary database later
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- ACTUATOR CONFIGURATION ---
# We are exposing all actuator endpoints over the web (health, metrics, info, etc)
# Note: In production, you'd only expose /health to the internet for security reasons
management.endpoints.web.exposure.include=*

# Kafka Producer Configuration
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
